name: Xcancel Discord Bot 247

on:
  schedule:
    # Menjalankan otomatis setiap 30 menit sekali
    - cron: '*/30 * * * *'
  workflow_dispatch: # Memungkinkan tombol 'Run workflow' manual di tab Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper Script
        run: python main.py

      - name: Auto Commit Log Database (Agar tidak duplikat)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add posted_tweets.json
          git commit -m "Update posted_tweets.json log [skip ci]" || exit 0
          git push
